export const FETCH_HOBBIES_REQUEST = 'FETCH_HOBBIES_REQUEST';
export const FETCH_HOBBIES_SUCCESS = 'FETCH_HOBBIES_SUCCESS';
export const FETCH_HOBBIES_FAILURE = 'FETCH_HOBBIES_FAILURE';
export const SELECT_HOBBY = 'SELECT_HOBBY';
export const UNSELECT_HOBBY = 'UNSELECT_HOBBY';